# Site title and subtitle. This is used in _includes/header.html
title: 'Avalara Developer'
subtitle: ''

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: 'developeravalaracom'

# if you use google analytics, add your tracking id here
google_analytics_id: ''

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2


plugins_dir:
  - jekyll-seo-tag. # generate cannoical url, twitter card, og, etc

# jekyll seo params start
twitter:
    username: avalara

facebook:
    publisher: https://www.facebook.com/avalara/

logo: /public/images/Avalara_logo.svg
# jekyll seo params end

host: 0.0.0.0

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/avalara/developer-dot'

# Default categories (in order) to appear in the navigation
sections: [
    ['doc', 'Documentation'],
    ['tut', 'Tutorial'],
    ['ref', 'Reference'],
    ['dev', 'Developers'],
    ['post', 'Posts']
]

gems:
    - jekyll-paginate

algolia:
    application_id: '19A6FWAAB3'
    index_name: 'developer-dot'
    settings:
        attributesForFaceting: ['doctype', 'product']


# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: [node_modules, dynamic, LICENSE, README.md, package.json, s3_website.yml, Gemfile, Gemfile.lock, _test, scripts]
include: ['_webinars']

# Use the kramdown Markdown renderer
markdown: kramdown
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]

paginate: 8
paginate_path: "/blog/page:num/"

# applies to _posts only for some reason
permalink: blog/:year/:month/:day/:title/
excerpt_separator: <!--more-->

collections:
  webinars:
    output: true
    permalink: /webinars/:year/:month/:day/

## Jekyll Archives configuration
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: archive-tag
  permalinks:
    category: 'blog/:name/'
